---
title: Task Entity
---
classDiagram
    class Task{
        -Long id
        -String title
        -String description
        -String status
        +getId() Long
        +getTitle() String
        +getDescription() String
        +getStatus() String
        +setId()
        +setTitle()
        +setDescription()
        +setStatus()
    }
